"""
This agent is a demo of the "SciAgents" abstraction.

This Demo_Agent stores all the models and their accuracies generated by both
investigators. It then updates the model selector to always use the most
accurate model.

---
More about SciAgents:

A SciAgent is used to group together multiple investigators that operate on the
same input / output DataTypes under one roof. It also has a "model selector"
task that runs in-stream, deciding what investigator and model to run for
inference.

The purpose of the Science Agent is to contain one physics property. The
investigator then provides the implementation.
This implementation can have an Active Learner, and publishes one surrogate.


The alternative is to have only an investigator, and put all the various
surrogates inside one active learning loop. This is absolutely acceptable (see
the m3dc1 investigator), though the SciAgent format is more generalizable and scalable.
It separates the concerns from training a specific surrogate architecture from
the decision making of what surrogate to train/run when.
"""

DO_PRINT = False
import asyncio
import json

import pandas as pd
from radical.asyncflow import WorkflowEngine
from digitaltwin.components import ModelInvestigator, TypedData, SciAgent
from digitaltwin.runtime import RuntimeAPI

from .demo_investigator1 import Demo_Investigator_1
from .demo_investigator2 import Demo_Investigator_2

from dtypes import *

import logging

logger = logging.getLogger(__name__)


class DEMO_Agent(SciAgent):
    def __init__(self, flow: WorkflowEngine):
        super().__init__(flow)
        self.flow = flow

        # no learning. Simple investigator
        self.investigator_1 = Demo_Investigator_1(flow)
        self.investigator_2 = Demo_Investigator_2(flow)

        self.model_inventory: list[dict] = []
        self.update_event = asyncio.Event()

        @self.flow.function_task
        async def model_select(in_data: TypedData, i_id=0, model_kwargs={}):
            return i_id, model_kwargs

        self.model_selector = model_select

    async def model_publish_cb(
        self, investigator: ModelInvestigator, model_args, acc_metrics
    ):
        # when a new model is published, add it to my model inventory
        model = {
            "investigator": investigator.get_id(),
            "model_args": json.dumps(model_args),
            "acc": acc_metrics.get("acc", 0),
        }
        self.model_inventory.append(model)
        self.update_event.set()

    async def main_loop(self, runtime: RuntimeAPI):
        # Start up the investigator
        runtime.start_investigator(self.investigator_1)
        runtime.start_investigator(self.investigator_2)
        runtime.subscribe_to_topic(runtime.ON_MODEL_PUBLISH, self.model_publish_cb)

        runtime.set_model_selection_task(self.model_selector)

        # default to investigator 1
        runtime.update_model_selector(i_id=self.investigator_1.get_id())

        while True:
            await self.update_event.wait()
            model_df = pd.DataFrame(self.model_inventory)

            # select the model with the best accuracy.
            sorted_df = model_df.sort_values(by="acc", ascending=False)
            investigator_out = int(sorted_df.iloc[0]["investigator"])

            m_args = json.loads(sorted_df.iloc[0]["model_args"])
            if DO_PRINT:
                print(
                    f"[Demo Agent]: Winner is Investigator {investigator_out + 1}, model: {m_args}"
                )
            runtime.update_model_selector(i_id=investigator_out, model_kwargs=m_args)
            del model_df
            self.update_event.clear()
